name: set-pac-path
description: "add pac cli to path so we can use it directly"

runs:
  using: "composite"
  steps:
    # to force download of microsoft/powerplatform-actions
    - if: false 
      name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0

      name: get-pac-path
      shell: pwsh
      run: |
        $actionsPath = "${{ runner.temp }}".Replace("_temp","_actions")
        if ($env:RUNNER_OS -eq "Windows") {
          $array = Get-ChildItem $actionsPath -Recurse | Where-Object{$_.FullName.EndsWith('pac\tools\pac.exe')}
        }
        else {
          $array = Get-ChildItem $actionsPath -Recurse | Where-Object{$_.FullName.EndsWith('pac_linux/tools/pac')}
        }
        $pacPath = $array[0].Directory.FullName
        "$pacPath" >> $env:GITHUB_PATH
