name: test

on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy-pre-to-pro:
    runs-on: windows-latest
    environment: MAIN        

    steps:
    - name: checkout action
      uses: actions/checkout@v3
      with:
        lfs: true
        
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
         environment-url: ${{vars.ENVIRONMENT_URL}}
         app-id: ${{vars.CLIENT_ID}}
         client-secret: ${{ secrets.CLIENT_SECRET }}
         tenant-id: ${{vars.TENANT_ID}}      

    - name: another-shell
      shell: cmd
      run: |
        echo ${{github.workspace}} 
        echo %Path%

    - name: set-pac-cli-path
      shell: powershell
      run: |
        Set-Location "..\..\_actions\microsoft\powerplatform-actions\v0\dist\pac\tools"
        $newPath = (Get-Location).Path
        $oldPath = [Environment]::GetEnvironmentVariable('PATH', 'Machine');
        [Environment]::SetEnvironmentVariable('PATH', "$newPath;$oldPath",'Machine');
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
        Set-Location "${{github.workspace}}"
        pac help
        [Environment]::GetEnvironmentVariable('PATH', 'Machine');
        [Environment]::GetEnvironmentVariable('PATH', 'User');

    - name: another-shell
      shell: cmd
      run: |
        echo "before refresh"
        echo %Path%
        refreshenv
        echo "after refresh"
        echo %Path%
        echo "now the github env"
        echo $PATH
        echo "and run"
        pac help
        
    - name: set-pac-cli-path
      shell: powershell
      run: |
        pac admin help
        pac auth list
        
