name: test

on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy-pre-to-pro:
    runs-on: windows-latest
    environment: INT         

    steps:

    - name: checkout action
      uses: actions/checkout@v3
      
    - name: login-azure
      uses: Azure/login@v1
      with:
        creds: |
          {
            clientId:${{vars.CLIENT_ID}},
            clientSecret:${{secrets.CLIENT_SECRET}},
            subscriptionId:b101f93a-d55e-49c9-b40d-60175ed2d684,
            tenantId:${{vars.TENANT_ID}}
          }

    # Deploy ARM template
    - name: check-arm-deploy
      uses: azure/arm-deploy@v1
      with:
        deploymentName: "Deploy eco-mpfc from github"
        subscriptionId: b101f93a-d55e-49c9-b40d-60175ed2d684,
        resourceGroupName: "DefaultResourceGroup-WEU"
        template: Azure/eco-mpfc/template.json
        parameters: Azure/eco-mpfc/parameters.json
        additionalArguments: "--what-if"

