name: pac-org-who

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set pac cli path
        run: echo "::add-path::${{ runner.workspace }}/pac-cli"

      - name: Run pac org who
        uses: microsoft/powerplatform-actions@v1
        with:
          command: 'pac org who'
