name: test

on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy-pre-to-pro:
    runs-on: windows-latest

    steps:

    - name: checkout action
      uses: actions/checkout@v3
      
    - name: download-pac-cli
      if: false
      uses: microsoft/powerplatform-actions/who-am-i@v0

    - name: set-pac-cli-path
      shell: pwsh
      run: |
        $pacPath = (Resolve-Path -Path "..\..\_actions\microsoft\powerplatform-actions\v0\dist\pac\tools").Path
        "$pacPath" >> $env:GITHUB_PATH

    - name: test
      env:
        preproduccionUrl: "https://integracio-eco-mpfc.crm4.dynamics.com/"
        sourceUser: "GGMZNT0003@gencat.cat"
        sourcePassword: "Avanade2023$"
      run: |
        pac auth create -u $env:preproduccionUrl -un $env:sourceUser -p $env:sourcePassword

    - name: test
      env:
        preproduccioUrl: "https://integracio-eco-mpfc.crm4.dynamics.com/"
      run: |
        pac org who
        echo GITHUB:
        echo "${{ toJson(github) }}"
        echo JOB:
        echo "${{ toJson(job) }}"
        echo STEPS:
        echo "${{ toJson(steps) }}"
        echo RUNNER:
        echo "${{ toJson(runner) }}"
        echo ENV:
        echo "${{ toJson(env) }}"
        echo VARS:
        echo "${{ toJson(vars) }}"
        echo INPUTS:
        echo "${{ toJson(inputs) }}"
        echo GITHUB_PATH:
        echo "$env:GITHUB_PATH"
     
