name: test

on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy-pre-to-pro:
    runs-on: windows-latest
    environment: MAIN        

    steps:
    - name: checkout action
      uses: actions/checkout@v3
      with:
        lfs: true
        
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
         environment-url: ${{vars.ENVIRONMENT_URL}}
         app-id: ${{vars.CLIENT_ID}}
         client-secret: ${{ secrets.CLIENT_SECRET }}
         tenant-id: ${{vars.TENANT_ID}}      

    - name: set-pro-tag action  
      shell: cmd
      run: |
        cd
        echo %Path%
        set "MY_PATH=%cd%"
        cd ..\..\_actions\microsoft\powerplatform-actions\v0\dist\pac\tools
        setx PATH "%PATH%;%cd%"
        refreshenv
        cd "%MY_PATH%"
        dir
        pac help

    - name: another-shell
      shell: cmd
      run: |
        cd
        echo %Path%
        pac help
